# Generated by Django 3.1.7 on 2021-03-05 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donations', '0011_auto_20210305_1816'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('story', models.CharField(max_length=600)),
                ('amount_needed', models.PositiveIntegerField(default=0, null=True)),
                ('approved', models.BooleanField(null=True)),
                ('donations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='donations.donation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
