# Generated by Django 3.1.7 on 2021-03-04 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donor',
        ),
        migrations.AddField(
            model_name='donation',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='donation',
            name='email',
            field=models.EmailField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='name',
            field=models.TextField(default='pre-alpha', max_length=255),
            preserve_default=False,
        ),
    ]
