# Generated by Django 3.1.7 on 2021-03-04 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_auto_20210304_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
