# Generated by Django 3.1.7 on 2021-03-05 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_auto_20210304_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='date',
        ),
    ]
