# Generated by Django 3.1.7 on 2021-03-05 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_remove_donation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
