# Generated by Django 3.1.7 on 2021-03-05 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0008_auto_20210305_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='date',
        ),
    ]
