# Generated by Django 3.1.7 on 2021-03-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0009_auto_20210305_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='amount',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
