# Generated by Django 3.1.7 on 2021-03-05 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20210305_2107'),
        ('donations', '0011_auto_20210305_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='property',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='properties.property'),
            preserve_default=False,
        ),
    ]
